### ISSUE TITLE
forgot an important exclamation mark

### ISSUE THREAD

**Issue by derbu** [lebochequirit/uberspace-renew-letsencrypt#1]
Hi,
I think you forgot an exclamation mark on line 41.
At the moment it will refresh your certificate every time you run it.
This is what the x509 man pages says:

> -checkend arg   - check whether the cert expires in the next arg seconds
>                    exit 1 if so, 0 if not

Try this on line 41:
`if ! openssl x509 -in $CERTDIR/cert.pem -checkend $WARNTIME -noout; then`

regards

**Comment by lebochequirit** [comment]
Blimey...
Must have missed that when cleaning up my trial and error (mostly error). Thank you.
